import { NextResponse } from "next/server";
import { z } from "zod";
import { requireSessionOrganization } from "@/lib/auth/session";
import { createAdminClient } from "@/lib/supabase/admin";
import { normalizeTaxId } from "@/lib/validation/identification";

export const runtime="nodejs";
const customerSchema=z.object({personType:z.enum(["INDIVIDUAL","COMPANY","FOREIGN"]),taxId:z.string().trim().max(20).optional().nullable(),legalName:z.string().trim().min(2).max(250),email:z.string().email().optional().or(z.literal("")),phone:z.string().trim().max(30).optional(),postalCode:z.string().trim().max(12).optional(),street:z.string().trim().max(160).optional(),addressNumber:z.string().trim().max(30).optional(),addressComplement:z.string().trim().max(100).optional(),neighborhood:z.string().trim().max(100).optional(),municipalRegistration:z.string().trim().max(50).optional(),municipalityCode:z.string().regex(/^\d{7}$/).optional(),state:z.string().regex(/^[A-Z]{2}$/).optional(),countryCode:z.string().regex(/^[A-Z]{2}$/).default("BR")});
const customerUpdateSchema=customerSchema.partial().extend({id:z.string().uuid()}).refine(input=>Object.keys(input).some(key=>key!=="id"),{message:"Informe ao menos um campo para alterar."});

export async function GET(request:Request){try{const session=await requireSessionOrganization();const search=new URL(request.url).searchParams.get("q")?.trim()??"";const admin=createAdminClient();let query=admin.from("customers").select("id,person_type,tax_id,legal_name,email,phone,municipality_code,state,country_code,postal_code,street,address_number,address_complement,neighborhood,municipal_registration").eq("organization_id",session.organizationId).order("legal_name").limit(50);if(search)query=query.or(`legal_name.ilike.%${search.replace(/[%,()]/g,"")}%,tax_id.ilike.%${normalizeTaxId(search)}%`);const{data,error}=await query;if(error)throw error;return NextResponse.json({customers:data??[]});}catch{return NextResponse.json({error:"Não foi possível carregar os tomadores."},{status:401});}}
export async function POST(request:Request){try{const session=await requireSessionOrganization();const input=customerSchema.parse(await request.json());const admin=createAdminClient();const {data,error}=await admin.from("customers").insert({organization_id:session.organizationId,person_type:input.personType,tax_id:input.taxId?normalizeTaxId(input.taxId):null,legal_name:input.legalName,email:input.email||null,phone:input.phone||null,postal_code:input.postalCode||null,street:input.street||null,address_number:input.addressNumber||null,address_complement:input.addressComplement||null,neighborhood:input.neighborhood||null,municipal_registration:input.municipalRegistration||null,municipality_code:input.municipalityCode||null,state:input.state||null,country_code:input.countryCode,address:{}}).select("id,legal_name,tax_id,person_type").single();if(error)throw error;return NextResponse.json({customer:data},{status:201});}catch(error){if(error instanceof z.ZodError)return NextResponse.json({error:"Revise os dados do tomador."},{status:400});return NextResponse.json({error:"Não foi possível salvar o tomador. Documento já pode estar cadastrado."},{status:422});}}
export async function PATCH(request:Request){try{const session=await requireSessionOrganization();const input=customerUpdateSchema.parse(await request.json());const update:Record<string,string|null>={};if(input.personType!==undefined)update.person_type=input.personType;if(input.taxId!==undefined)update.tax_id=input.taxId?normalizeTaxId(input.taxId):null;if(input.legalName!==undefined)update.legal_name=input.legalName;if(input.email!==undefined)update.email=input.email||null;if(input.phone!==undefined)update.phone=input.phone||null;if(input.postalCode!==undefined)update.postal_code=input.postalCode||null;if(input.street!==undefined)update.street=input.street||null;if(input.addressNumber!==undefined)update.address_number=input.addressNumber||null;if(input.addressComplement!==undefined)update.address_complement=input.addressComplement||null;if(input.neighborhood!==undefined)update.neighborhood=input.neighborhood||null;if(input.municipalRegistration!==undefined)update.municipal_registration=input.municipalRegistration||null;if(input.municipalityCode!==undefined)update.municipality_code=input.municipalityCode||null;if(input.state!==undefined)update.state=input.state||null;if(input.countryCode!==undefined)update.country_code=input.countryCode;const admin=createAdminClient();const{data,error}=await admin.from("customers").update(update).eq("id",input.id).eq("organization_id",session.organizationId).select("id,legal_name,tax_id,person_type").maybeSingle();if(error)throw error;if(!data)return NextResponse.json({error:"Tomador não encontrado."},{status:404});return NextResponse.json({customer:data});}catch(error){if(error instanceof z.ZodError)return NextResponse.json({error:"Revise os dados do tomador."},{status:400});return NextResponse.json({error:"Não foi possível atualizar o tomador."},{status:422});}}
