import { NextResponse } from "next/server";
import { z } from "zod";
import { requireOfficeSession } from "@/lib/auth/session";
import { createAdminClient } from "@/lib/supabase/admin";

export const runtime="nodejs";
const payload=z.object({nationalServiceCodeId:z.uuid(),name:z.string().trim().min(2).max(160),defaultDescription:z.string().trim().max(1000).optional(),municipalServiceCode:z.string().regex(/^\d{2}\.\d{2}\.\d{2}\.\d{3}$/).optional().or(z.literal("")),dpsMunicipalTaxCode:z.string().regex(/^\d{3}$/).optional().or(z.literal("")),serviceLocationMunicipalityCode:z.string().regex(/^\d{7}$/).optional().or(z.literal("")),active:z.boolean().optional()});
const patch=payload.omit({nationalServiceCodeId:true}).partial().extend({id:z.uuid()});
export async function GET(_:Request,{params}:{params:Promise<{id:string}>}){try{await requireOfficeSession();const{id}=await params;const{data,error}=await createAdminClient().from("service_templates").select("id,name,default_description,active,national_tax_code,municipal_service_code,dps_municipal_tax_code,service_location_municipality_code,national_service_codes(display_code,description)").eq("organization_id",id).order("name");if(error)throw error;return NextResponse.json({services:data??[]});}catch{return NextResponse.json({error:"Acesso do escritório necessário."},{status:403});}}
export async function POST(request:Request,{params}:{params:Promise<{id:string}>}){try{await requireOfficeSession();const{id:organizationId}=await params;const input=payload.parse(await request.json());const db=createAdminClient();const{data:code,error:codeError}=await db.from("national_service_codes").select("id,code").eq("id",input.nationalServiceCodeId).eq("active",true).single();if(codeError||!code)return NextResponse.json({error:"Código nacional indisponível."},{status:422});const{data,error}=await db.from("service_templates").insert({organization_id:organizationId,national_service_code_id:code.id,national_tax_code:code.code,name:input.name,default_description:input.defaultDescription||null,municipal_service_code:input.municipalServiceCode||null,dps_municipal_tax_code:input.dpsMunicipalTaxCode||null,service_location_municipality_code:input.serviceLocationMunicipalityCode||null,active:input.active??true}).select("id").single();if(error)throw error;return NextResponse.json({service:data},{status:201});}catch(error){return NextResponse.json({error:error instanceof z.ZodError?"Revise os campos do serviço.":"Não foi possível salvar o serviço."},{status:422});}}
export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){try{await requireOfficeSession();const{id:organizationId}=await params;const input=patch.parse(await request.json());const{error}=await createAdminClient().from("service_templates").update({name:input.name,default_description:input.defaultDescription,municipal_service_code:input.municipalServiceCode||null,dps_municipal_tax_code:input.dpsMunicipalTaxCode||null,service_location_municipality_code:input.serviceLocationMunicipalityCode||null,active:input.active}).eq("id",input.id).eq("organization_id",organizationId);if(error)throw error;return NextResponse.json({ok:true});}catch{return NextResponse.json({error:"Não foi possível atualizar o serviço."},{status:422});}}
