import Link from "next/link";
import { ArrowRight, CircleAlert } from "lucide-react";
import { redirect } from "next/navigation";
import { EmptyState, PageHeader, StatusBadge, formatDateTime } from "@/components/ui-kit";
import { getCertificateOperationalState, getOperationalPriority, operationalAgeHours, type OperationalItem, type OperationalItemType } from "@/lib/operations/queue";
import { requireOfficeSession } from "@/lib/auth/session";
import { createAdminClient } from "@/lib/supabase/admin";

function priorityTone(priority: string): "danger" | "warning" | "info" { return priority === "CRITICAL" ? "danger" : priority === "HIGH" ? "warning" : "info"; }

export default async function OperationalQueuePage() {
  try { await requireOfficeSession(); } catch { redirect("/app?notice=office"); }
  const db = createAdminClient();
  const [invoicesResult, certificatesResult, servicesResult, organizationsResult, accessesResult, cancellationsResult] = await Promise.all([
    db.from("invoices").select("id,organization_id,status,created_at,updated_at,amount_cents,customers(legal_name),organizations(legal_name)").in("status", ["UNKNOWN", "REJECTED"]).order("updated_at", { ascending: false }).limit(250),
    db.from("digital_certificates").select("id,organization_id,status,valid_until,created_at,organizations(legal_name)").is("replaced_at", null).order("valid_until").limit(250),
    db.from("service_templates").select("id,organization_id,name,workflow_status,submitted_at,updated_at,organizations(legal_name)").in("workflow_status", ["PENDING_REVIEW", "NEEDS_INFO"]).order("submitted_at", { ascending: true }).limit(250),
    db.from("organizations").select("id,legal_name,status,emission_blocked,created_at,updated_at").or("status.neq.ACTIVE,emission_blocked.eq.true").limit(250),
    db.from("client_accesses").select("id,organization_id,enabled,created_at,organizations(legal_name)").eq("enabled", false).limit(250),
    db.from("cancellation_requests").select("id,organization_id,status,created_at,updated_at,organizations(legal_name)").in("status", ["REQUESTED", "UNDER_REVIEW", "APPROVED", "PROCESSING", "UNKNOWN"]).order("updated_at", { ascending: false }).limit(250),
  ]);
  const items: OperationalItem[] = [];
  for (const invoice of invoicesResult.data ?? []) { const type = invoice.status === "UNKNOWN" ? "INVOICE_UNKNOWN" : "INVOICE_REJECTED" as OperationalItemType; const organizationName = invoice.organizations?.[0]?.legal_name ?? "Empresa"; items.push({ id: `invoice-${invoice.id}`, organizationId: invoice.organization_id, organizationName, type, title: type === "INVOICE_UNKNOWN" ? "NFS-e em confirmação" : "NFS-e não emitida", description: invoice.customers?.[0]?.legal_name ?? "Revisar a nota fiscal.", priority: getOperationalPriority(type, { ageHours: operationalAgeHours(invoice.created_at) }), createdAt: invoice.created_at, updatedAt: invoice.updated_at, href: `/admin/notas/${invoice.id}` }); }
  for (const certificate of certificatesResult.data ?? []) { const state = getCertificateOperationalState({ status: certificate.status, validUntil: certificate.valid_until }); if (!state) continue; const organizationName = certificate.organizations?.[0]?.legal_name ?? "Empresa"; items.push({ id: `certificate-${certificate.id}`, organizationId: certificate.organization_id, organizationName, type: state.type, title: state.type === "CERTIFICATE_EXPIRED" ? "Certificado vencido" : "Certificado próximo do vencimento", description: state.daysRemaining < 0 ? "O certificado precisa ser substituído." : `Vence em ${state.daysRemaining} dia(s).`, priority: getOperationalPriority(state.type), createdAt: certificate.created_at, updatedAt: certificate.valid_until, href: `/admin/empresas/${certificate.organization_id}?tab=certificate` }); }
  for (const service of servicesResult.data ?? []) { const type = service.workflow_status === "PENDING_REVIEW" ? "SERVICE_PENDING_REVIEW" : "SERVICE_NEEDS_INFO" as OperationalItemType; items.push({ id: `service-${service.id}`, organizationId: service.organization_id, organizationName: service.organizations?.[0]?.legal_name ?? "Empresa", type, title: type === "SERVICE_PENDING_REVIEW" ? "Serviço aguardando análise" : "Serviço precisa de informação", description: service.name, priority: getOperationalPriority(type), createdAt: service.submitted_at ?? service.updated_at, updatedAt: service.updated_at, href: `/admin/empresas/${service.organization_id}?tab=services&service=${service.id}` }); }
  for (const organization of organizationsResult.data ?? []) items.push({ id: `organization-${organization.id}`, organizationId: organization.id, organizationName: organization.legal_name, type: "ORGANIZATION_NOT_READY", title: "Onboarding ou prontidão pendente", description: organization.emission_blocked ? "A emissão permanece bloqueada." : `Status atual: ${organization.status}.`, priority: getOperationalPriority("ORGANIZATION_NOT_READY"), createdAt: organization.created_at, updatedAt: organization.updated_at, href: `/admin/empresas/${organization.id}` });
  for (const access of accessesResult.data ?? []) items.push({ id: `access-${access.id}`, organizationId: access.organization_id, organizationName: access.organizations?.[0]?.legal_name ?? "Empresa", type: "CLIENT_ACCESS_INVALID", title: "Acesso do cliente pendente", description: "O acesso principal do cliente está bloqueado ou pendente.", priority: getOperationalPriority("CLIENT_ACCESS_INVALID"), createdAt: access.created_at, updatedAt: access.created_at, href: `/admin/empresas/${access.organization_id}?tab=users` });
  for (const cancellation of cancellationsResult.data ?? []) items.push({ id: `cancellation-${cancellation.id}`, organizationId: cancellation.organization_id, organizationName: cancellation.organizations?.[0]?.legal_name ?? "Empresa", type: "CANCELLATION_PENDING", title: "Cancelamento aguardando análise", description: cancellation.status === "UNKNOWN" ? "A situação do cancelamento precisa ser confirmada." : "A solicitação ainda não foi concluída.", priority: getOperationalPriority("CANCELLATION_PENDING"), createdAt: cancellation.created_at, updatedAt: cancellation.updated_at, href: "/admin/cancelamentos" });
  const order = { CRITICAL: 0, HIGH: 1, NORMAL: 2 } as const;
  items.sort((a, b) => order[a.priority] - order[b.priority] || new Date(a.updatedAt).getTime() - new Date(b.updatedAt).getTime());
  return <div className="page v2-page"><PageHeader title="Pendências" description="Fila operacional consolidada a partir dos dados reais do sistema." />
    <section className="v2-panel v2-table-panel"><div className="v2-panel-heading"><div><h2>Requer atenção</h2><p>{items.length} item(ns) operacional(is)</p></div></div>{items.length ? <div className="v2-table-scroll"><table className="v2-table"><thead><tr><th>Prioridade</th><th>Empresa</th><th>Tipo</th><th>Descrição</th><th>Atualização</th><th>Ação</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><StatusBadge tone={priorityTone(item.priority)}>{item.priority === "CRITICAL" ? "Crítica" : item.priority === "HIGH" ? "Alta" : "Normal"}</StatusBadge></td><td>{item.organizationName}</td><td className="v2-table-primary">{item.title}</td><td>{item.description}</td><td>{formatDateTime(item.updatedAt)}</td><td><Link className="button ghost compact" href={item.href}>Abrir<ArrowRight size={15} /></Link></td></tr>)}</tbody></table></div> : <EmptyState title="Nenhuma pendência operacional" description="Não há itens que exijam ação agora." action={<Link className="button secondary" href="/admin"><CircleAlert size={17} />Voltar à visão geral</Link>} />}</section>
  </div>;
}
