"use client";
import { useEffect,useState } from "react";
import { Pencil,Plus,Search,X } from "lucide-react";

type Service={id:string;name:string;default_description:string|null;active:boolean;national_service_code_id:string;national_tax_code:string;municipal_service_code:string|null;dps_municipal_tax_code:string|null;service_location_municipality_code:string|null;national_service_codes:{display_code:string;description:string}|null};
type Code={id:string;code:string;display_code:string;item:string;subitem:string|null;national_split:string|null;description:string};
const blank={name:"",defaultDescription:"",municipalServiceCode:"",dpsMunicipalTaxCode:"",serviceLocationMunicipalityCode:""};
export function ServiceManager({organizationId,initialServices,catalogAvailable}:{organizationId:string;initialServices:Service[];catalogAvailable:boolean}){
 const[services,setServices]=useState(initialServices),[open,setOpen]=useState(false),[editingId,setEditingId]=useState<string|null>(null),[query,setQuery]=useState(""),[codes,setCodes]=useState<Code[]>([]),[selected,setSelected]=useState<Code|null>(null),[form,setForm]=useState(blank),[error,setError]=useState(""),[saving,setSaving]=useState(false);
 useEffect(()=>{if(!open||!catalogAvailable)return;const controller=new AbortController();const timer=setTimeout(()=>fetch(`/api/admin/national-service-codes?q=${encodeURIComponent(query)}`,{signal:controller.signal}).then(r=>r.json()).then(x=>setCodes(x.codes??[])).catch(()=>setError("Não foi possível pesquisar o catálogo.")),180);return()=>{clearTimeout(timer);controller.abort();};},[open,query,catalogAvailable]);
 const canSave=selected&&form.name.trim().length>1;
 async function save(){if(!canSave)return;setSaving(true);setError("");const response=await fetch(`/api/admin/organizations/${organizationId}/services`,{method:editingId?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(editingId?{id:editingId,...form}:{nationalServiceCodeId:selected.id,...form})});const result=await response.json();setSaving(false);if(!response.ok){setError(result.error??"Não foi possível salvar o serviço.");return;}setOpen(false);setEditingId(null);setSelected(null);setForm(blank);window.location.reload();}
 async function toggle(service:Service){const response=await fetch(`/api/admin/organizations/${organizationId}/services`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:service.id,name:service.name,defaultDescription:service.default_description??"",municipalServiceCode:service.municipal_service_code??"",dpsMunicipalTaxCode:service.dps_municipal_tax_code??"",serviceLocationMunicipalityCode:service.service_location_municipality_code??"",active:!service.active})});if(response.ok)setServices(rows=>rows.map(row=>row.id===service.id?{...row,active:!row.active}:row));}
 function edit(service:Service){setEditingId(service.id);setSelected({id:service.national_service_code_id,code:service.national_tax_code,display_code:service.national_service_codes?.display_code??service.national_tax_code,item:"",subitem:null,national_split:null,description:service.national_service_codes?.description??"Código nacional"});setForm({name:service.name,defaultDescription:service.default_description??"",municipalServiceCode:service.municipal_service_code??"",dpsMunicipalTaxCode:service.dps_municipal_tax_code??"",serviceLocationMunicipalityCode:service.service_location_municipality_code??""});setOpen(true);}
 return <section className="section"><div className="section-toolbar"><div><h2 className="section-title">Serviços da empresa</h2><p>Somente templates ativos aparecem para o cliente no momento da emissão.</p></div><button className="button primary" type="button" onClick={()=>{setEditingId(null);setSelected(null);setForm(blank);setOpen(true);}} disabled={!catalogAvailable}><Plus size={18}/>Adicionar serviço</button></div>{!catalogAvailable?<div className="empty-state"><strong>Catálogo nacional ainda não foi importado.</strong><p>Use a importação oficial do Anexo B antes de criar templates.</p></div>:services.length?<div className="service-list">{services.map(service=><div className="service-row" key={service.id}><div><strong>{service.name}</strong><span>{service.national_service_codes?.display_code??service.national_tax_code} · {service.national_service_codes?.description??"Código nacional"}</span></div><span className={`status ${service.active?"":"warning"}`}>{service.active?"Ativo":"Inativo"}</span><div><button className="button ghost" type="button" onClick={()=>edit(service)}><Pencil size={16}/>Editar</button><button className="button ghost" type="button" onClick={()=>toggle(service)}>{service.active?"Desativar":"Ativar"}</button></div></div>)}</div>:<div className="empty-state"><strong>Nenhum serviço cadastrado.</strong><p>Escolha um código nacional oficial e complete somente os campos confirmados.</p></div>}
 {open&&<div className="modal-backdrop" role="dialog" aria-modal="true" aria-label={editingId?"Editar serviço":"Adicionar serviço"}><div className="modal"><div className="modal-header"><div><h2>{editingId?"Editar serviço":"Adicionar serviço"}</h2><p>Campos municipais não são inferidos.</p></div><button className="icon-button" type="button" onClick={()=>setOpen(false)} aria-label="Fechar"><X/></button></div>{!selected?<><label className="search-field"><Search size={18}/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Código, item ou descrição"/></label><div className="catalog-results">{codes.map(code=><button className="catalog-option" type="button" key={code.id} onClick={()=>{setSelected(code);setForm({...blank,name:code.description.slice(0,120)});}}><span className="catalog-code">{code.display_code}</span><span>{code.description}</span><b>Adicionar</b></button>)}{!codes.length&&<p>Nenhum código encontrado.</p>}</div></>:<div className="service-form">{!editingId&&<button className="text-button" type="button" onClick={()=>setSelected(null)}>← Voltar ao catálogo</button>}<div className="selected-code"><strong>{selected.display_code}</strong><span>{selected.description}</span></div><label>Nome amigável<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Descrição padrão<textarea value={form.defaultDescription} onChange={e=>setForm({...form,defaultDescription:e.target.value})}/></label><label>Código municipal de parametrização <em>opcional até confirmação</em><input placeholder="00.00.00.000" value={form.municipalServiceCode} onChange={e=>setForm({...form,municipalServiceCode:e.target.value})}/></label><label>cTribMun DPS <em>opcional até confirmação</em><input placeholder="000" value={form.dpsMunicipalTaxCode} onChange={e=>setForm({...form,dpsMunicipalTaxCode:e.target.value})}/></label><label>Município de prestação <em>opcional até confirmação</em><input placeholder="Código IBGE" value={form.serviceLocationMunicipalityCode} onChange={e=>setForm({...form,serviceLocationMunicipalityCode:e.target.value})}/></label>{error&&<p className="alert error">{error}</p>}<div className="form-actions"><button className="button secondary" type="button" onClick={()=>setOpen(false)}>Cancelar</button><button className="button primary" type="button" disabled={!canSave||saving} onClick={save}>{saving?"Salvando…":"Salvar template"}</button></div></div>}</div></div>}</section>;
}
