import type { FiscalDocumentDomain } from "../types";
import type { IssRateSource } from "../service-fiscal-reference";
import { SafeFiscalError } from "../errors";
import { buildDpsIdentifier } from "./identifier";

export type DpsPerson={taxId?:string;foreignTaxId?:string;noForeignTaxIdReason?:"0"|"1"|"2";municipalRegistration?:string;emitMunicipalRegistration?:boolean;emitName?:boolean;emitAddress?:boolean;name:string;address?:{municipalityCode?:string;postalCode?:string;countryCode?:string;postalAddressCode?:string;city?:string;stateOrProvince?:string;street:string;number:string;complement?:string;neighborhood:string};phone?:string;email?:string};
export type DpsFiscalConfiguration={regime:{simpleNational:"1"|"2"|"3";simpleAssessment?:"1"|"2"|"3";special:"0"|"1"|"2"|"3"|"4"|"5"|"6"|"9"};iss:{taxation:"1"|"2"|"3"|"4";withholding:"1"|"2"|"3";rateSource:IssRateSource;rateBasisPoints?:number;countryOfResult?:string;immunityType?:"0"|"1"|"2"|"3"|"4"|"5";suspension?:{type:"1"|"2";processNumber:string};benefit?:{number:string;reductionAmountCents?:number;reductionBasisPoints?:number}};totalTaxes:{indicator:"0"}|{percentages:{federalBasisPoints:number;stateBasisPoints:number;municipalBasisPoints:number}}|{amounts:{federalCents:number;stateCents:number;municipalCents:number}};federalRetentions?:{pisCofins?:{cst:string;type?:string};socialSecurityCents?:number;irrfCents?:number;csllCents?:number};ibsCbsRequired?:boolean};
export type DpsModel={id:string;environment:"2";emittedAt:string;applicationVersion:string;series:string;number:bigint;competence:string;issuingMunicipalityCode:string;issuer:DpsPerson;customer?:DpsPerson;service:{location:{municipalityCode?:string;countryCode?:string};nationalTaxCode:string;municipalTaxCode?:string;nbsCode?:string;description:string};amountCents:number;fiscal:DpsFiscalConfiguration};

export function mapToDpsModel(document:FiscalDocumentDomain,input:{issuer:DpsPerson;customer?:DpsPerson;serviceLocation:{municipalityCode?:string;countryCode?:string};dpsMunicipalTaxCode?:string;nbsCode?:string;fiscal:DpsFiscalConfiguration;emittedAt:string;applicationVersion:string}):DpsModel{
  if(!input.issuer.name||!input.issuer.taxId||!document.issuer.municipalityCode||!input.serviceLocation.municipalityCode&&!input.serviceLocation.countryCode||!document.service.nationalTaxCode||!document.service.description||!input.fiscal.iss.withholding||!input.fiscal.regime.special)throw new SafeFiscalError("FISCAL_CONFIGURATION_INCOMPLETE","Faltam dados obrigatórios para gerar a DPS.");
  if(input.fiscal.ibsCbsRequired)throw new SafeFiscalError("FISCAL_CONFIGURATION_INCOMPLETE","A classificação IBS/CBS desta operação ainda não está parametrizada.");
  if(!["PARAMETRIZED_BY_NATIONAL","EMITTER_PROVIDED"].includes(input.fiscal.iss.rateSource))throw new SafeFiscalError("FISCAL_CONFIGURATION_INCOMPLETE","A origem da alíquota do ISS não está definida.");
  if(input.fiscal.iss.rateSource==="EMITTER_PROVIDED"&&input.fiscal.iss.rateBasisPoints===undefined)throw new SafeFiscalError("FISCAL_CONFIGURATION_INCOMPLETE","A alíquota do ISS desta operação não está definida.");
  if(input.fiscal.iss.rateSource==="PARAMETRIZED_BY_NATIONAL"&&input.fiscal.iss.rateBasisPoints!==undefined)throw new SafeFiscalError("FISCAL_CONFIGURATION_INCOMPLETE","A alíquota parametrizada pelo Sistema Nacional não deve ser informada pelo emissor.");
  const id=buildDpsIdentifier({municipalityCode:document.issuer.municipalityCode,taxId:input.issuer.taxId,series:document.dps.series,number:document.dps.number});
  if(input.dpsMunicipalTaxCode!==undefined&&!/^\d{3}$/.test(input.dpsMunicipalTaxCode))throw new SafeFiscalError("FISCAL_SERVICE_MAPPING_MISSING","O código municipal da DPS não está mapeado corretamente.");
  if(input.nbsCode!==undefined&&!/^\d{9}$/.test(input.nbsCode))throw new SafeFiscalError("FISCAL_SERVICE_MAPPING_MISSING","O código NBS não está mapeado corretamente.");
  return {id,environment:"2",emittedAt:input.emittedAt,applicationVersion:input.applicationVersion,series:document.dps.series,number:document.dps.number,competence:document.serviceDate,issuingMunicipalityCode:document.issuer.municipalityCode,issuer:input.issuer,...(input.customer?{customer:input.customer}:{}),service:{location:input.serviceLocation,nationalTaxCode:document.service.nationalTaxCode,...(input.dpsMunicipalTaxCode?{municipalTaxCode:input.dpsMunicipalTaxCode}:{}),...(input.nbsCode?{nbsCode:input.nbsCode}:{}),description:document.service.description},amountCents:document.amountCents,fiscal:input.fiscal};
}
