import { create } from "xmlbuilder2";
import type { DpsModel,DpsPerson } from "./model";

const namespace="http://www.sped.fazenda.gov.br/nfse";
const money=(cents:number)=>`${Math.floor(cents/100)}.${String(Math.abs(cents%100)).padStart(2,"0")}`;
const percentage=(basisPoints:number)=>`${Math.floor(basisPoints/100)}.${String(Math.abs(basisPoints%100)).padStart(2,"0")}`;
function identity(parent:ReturnType<ReturnType<typeof create>["ele"]>,person:DpsPerson){const taxId=person.taxId?.replace(/\D/g,"");if(taxId?.length===14)parent.ele("CNPJ").txt(taxId);else if(taxId?.length===11)parent.ele("CPF").txt(taxId);else if(person.foreignTaxId)parent.ele("NIF").txt(person.foreignTaxId);else parent.ele("cNaoNIF").txt(person.noForeignTaxIdReason??"0");if(person.municipalRegistration)parent.ele("IM").txt(person.municipalRegistration);parent.ele("xNome").txt(person.name);if(person.address){const end=parent.ele("end");const address=person.address;if(address.countryCode&&address.countryCode!=="BR")end.ele("endExt").ele("cPais").txt(address.countryCode).up().ele("cEndPost").txt(address.postalAddressCode??"").up().ele("xCidade").txt(address.city??"").up().ele("xEstProvReg").txt(address.stateOrProvince??"");else end.ele("endNac").ele("cMun").txt(address.municipalityCode??"").up().ele("CEP").txt(address.postalCode?.replace(/\D/g,"")??"");end.ele("xLgr").txt(address.street).up().ele("nro").txt(address.number);if(address.complement)end.ele("xCpl").txt(address.complement);end.ele("xBairro").txt(address.neighborhood);}if(person.phone)parent.ele("fone").txt(person.phone.replace(/\D/g,""));if(person.email)parent.ele("email").txt(person.email);}

export function buildDpsXml(model:DpsModel){
  const document=create({version:"1.0",encoding:"UTF-8"}).ele("DPS",{xmlns:namespace,versao:"1.01"});
  const info=document.ele("infDPS",{Id:model.id});
  info.ele("tpAmb").txt(model.environment).up().ele("dhEmi").txt(model.emittedAt).up().ele("verAplic").txt(model.applicationVersion).up().ele("serie").txt(model.series).up().ele("nDPS").txt(model.number.toString()).up().ele("dCompet").txt(model.competence).up().ele("tpEmit").txt("1").up().ele("cLocEmi").txt(model.issuingMunicipalityCode);
  const prest=info.ele("prest");identity(prest,model.issuer);const reg=prest.ele("regTrib");reg.ele("opSimpNac").txt(model.fiscal.regime.simpleNational);if(model.fiscal.regime.simpleAssessment)reg.ele("regApTribSN").txt(model.fiscal.regime.simpleAssessment);reg.ele("regEspTrib").txt(model.fiscal.regime.special);
  if(model.customer){const toma=info.ele("toma");identity(toma,model.customer);}
  const serv=info.ele("serv");const loc=serv.ele("locPrest");if(model.service.location.municipalityCode)loc.ele("cLocPrestacao").txt(model.service.location.municipalityCode);else loc.ele("cPaisPrestacao").txt(model.service.location.countryCode!);const code=serv.ele("cServ");code.ele("cTribNac").txt(model.service.nationalTaxCode);if(model.service.municipalTaxCode)code.ele("cTribMun").txt(model.service.municipalTaxCode);code.ele("xDescServ").txt(model.service.description);
  const values=info.ele("valores");values.ele("vServPrest").ele("vServ").txt(money(model.amountCents));const trib=values.ele("trib");const iss=trib.ele("tribMun");iss.ele("tribISSQN").txt(model.fiscal.iss.taxation);if(model.fiscal.iss.countryOfResult)iss.ele("cPaisResult").txt(model.fiscal.iss.countryOfResult);if(model.fiscal.iss.immunityType)iss.ele("tpImunidade").txt(model.fiscal.iss.immunityType);if(model.fiscal.iss.suspension)iss.ele("exigSusp").ele("tpSusp").txt(model.fiscal.iss.suspension.type).up().ele("nProcesso").txt(model.fiscal.iss.suspension.processNumber);if(model.fiscal.iss.benefit){const benefit=iss.ele("BM");benefit.ele("nBM").txt(model.fiscal.iss.benefit.number);if(model.fiscal.iss.benefit.reductionAmountCents!==undefined)benefit.ele("vRedBCBM").txt(money(model.fiscal.iss.benefit.reductionAmountCents));else if(model.fiscal.iss.benefit.reductionBasisPoints!==undefined)benefit.ele("pRedBCBM").txt(percentage(model.fiscal.iss.benefit.reductionBasisPoints));}iss.ele("tpRetISSQN").txt(model.fiscal.iss.withholding);if(model.fiscal.iss.rateBasisPoints!==undefined)iss.ele("pAliq").txt(percentage(model.fiscal.iss.rateBasisPoints));
  const total=trib.ele("totTrib");if("indicator" in model.fiscal.totalTaxes)total.ele("indTotTrib").txt(model.fiscal.totalTaxes.indicator);else if("percentages" in model.fiscal.totalTaxes){const p=total.ele("pTotTrib");p.ele("pTotTribFed").txt(percentage(model.fiscal.totalTaxes.percentages.federalBasisPoints)).up().ele("pTotTribEst").txt(percentage(model.fiscal.totalTaxes.percentages.stateBasisPoints)).up().ele("pTotTribMun").txt(percentage(model.fiscal.totalTaxes.percentages.municipalBasisPoints));}else {const m=total.ele("vTotTrib");m.ele("vTotTribFed").txt(money(model.fiscal.totalTaxes.amounts.federalCents)).up().ele("vTotTribEst").txt(money(model.fiscal.totalTaxes.amounts.stateCents)).up().ele("vTotTribMun").txt(money(model.fiscal.totalTaxes.amounts.municipalCents));}
  return document.end({prettyPrint:false});
}
