import "server-only";
import { z } from "zod";
import { createAdminClient } from "@/lib/supabase/admin";
import { SafeFiscalError } from "./errors";
import { MunicipalParametersProvider, issPercentToBasisPoints, parseMunicipalServiceCode } from "./municipal-parameters/client";
const dpsTaxConfigurationSchema=z.object({iss:z.object({withholdingType:z.enum(["1","2","3"]),benefitNumber:z.string().min(1).optional()}),regime:z.object({simpleNational:z.enum(["1","2","3"]),simpleAssessment:z.enum(["1","2","3"]).optional(),special:z.enum(["0","1","2","3","4","5","6","9"])}),totalTaxes:z.object({indicator:z.literal("0")})});
const storedDpsTaxConfigurationSchema=z.union([dpsTaxConfigurationSchema,z.object({version:z.literal(1),form:z.unknown(),technical:dpsTaxConfigurationSchema.optional()})]);
export type FiscalResolutionInput={municipalityCode:string;nationalTaxCode:string;municipalServiceCode?:string|null;taxRegime:"SIMPLES_NACIONAL"|"LUCRO_PRESUMIDO"|"LUCRO_REAL";reviewedAt?:string|null;serviceDate:string;dpsConfiguration:unknown};
export type FiscalResolution={municipalityCode:string;nationalTaxCode:string;municipalServiceCode:string;iss:{rateBasisPoints:number;withholdingType:"1"|"2"|"3";source:"MUNICIPAL_INTEGRATION"};retention:{officialRulesChecked:true};dpsConfiguration:z.infer<typeof dpsTaxConfigurationSchema>;source:"MUNICIPAL_PARAMETERS";validity:{validFrom:string;validUntil?:string}};
export async function resolveFiscalConfiguration(input:FiscalResolutionInput):Promise<FiscalResolution>{if(!input.reviewedAt)throw new SafeFiscalError("FISCAL_CONFIGURATION_INCOMPLETE","Uma configuração fiscal desta empresa precisa ser revisada pelo escritório antes da emissão.");if(!input.municipalServiceCode)throw new SafeFiscalError("FISCAL_SERVICE_MAPPING_MISSING","Uma configuração fiscal desta empresa precisa ser revisada pelo escritório antes da emissão.");let dpsConfiguration:z.infer<typeof dpsTaxConfigurationSchema>;try{const stored=storedDpsTaxConfigurationSchema.parse(input.dpsConfiguration);dpsConfiguration="version" in stored?(stored.technical??(()=>{throw new Error("technical configuration pending")})()):stored;}catch{throw new SafeFiscalError("FISCAL_CONFIGURATION_INCOMPLETE","Uma configuração técnica da DPS ainda precisa ser revisada pelo escritório antes da emissão.");}const serviceCode=parseMunicipalServiceCode(input.municipalServiceCode);const admin=createAdminClient();const{data:cached}=await admin.from("municipal_tax_rules").select("incidence,iss_rate_percent,valid_from,valid_until").eq("municipality_code",input.municipalityCode).eq("service_code",serviceCode).lte("valid_from",`${input.serviceDate}T23:59:59Z`).or(`valid_until.is.null,valid_until.gte.${input.serviceDate}T00:00:00Z`).order("valid_from",{ascending:false}).limit(1).maybeSingle();const provider=new MunicipalParametersProvider();const rule=cached??await fetchRule(input.municipalityCode,serviceCode,input.serviceDate,provider);await Promise.all([provider.getRetentions({municipalityCode:input.municipalityCode,competence:input.serviceDate}),...(dpsConfiguration.regime.special!=="0"?[provider.getSpecialRegimes({municipalityCode:input.municipalityCode,serviceCode,competence:input.serviceDate})]:[]),...(dpsConfiguration.iss.benefitNumber?[provider.getBenefit({municipalityCode:input.municipalityCode,benefitNumber:dpsConfiguration.iss.benefitNumber,competence:input.serviceDate})]:[])]);if(rule.incidence!=="SIM"||rule.iss_rate_percent===null)throw new SafeFiscalError("FISCAL_CONFIGURATION_INCOMPLETE","Uma configuração fiscal desta empresa precisa ser revisada pelo escritório antes da emissão.");return{municipalityCode:input.municipalityCode,nationalTaxCode:input.nationalTaxCode,municipalServiceCode:serviceCode,iss:{rateBasisPoints:issPercentToBasisPoints(Number(rule.iss_rate_percent)),withholdingType:dpsConfiguration.iss.withholdingType,source:"MUNICIPAL_INTEGRATION"},retention:{officialRulesChecked:true},dpsConfiguration,source:"MUNICIPAL_PARAMETERS",validity:{validFrom:rule.valid_from,...(rule.valid_until?{validUntil:rule.valid_until}:{})}};}
async function fetchRule(municipalityCode:string,serviceCode:string,competence:string,provider:MunicipalParametersProvider){const response=await provider.getAliquota({municipalityCode,serviceCode,competence});const item=response.aliquotas[serviceCode].find(value=>!value.DtFim||value.DtFim>=`${competence}T00:00:00`)??response.aliquotas[serviceCode][0];const row={municipality_code:municipalityCode,service_code:serviceCode,incidence:item.Incidencia,iss_rate_percent:item.Aliq,valid_from:item.DtIni,valid_until:item.DtFim,source:"ADN_PRODUCTION_RESTRICTED",source_version:null,fetched_at:new Date().toISOString()};const{error}=await createAdminClient().from("municipal_tax_rules").upsert(row,{onConflict:"municipality_code,service_code,incidence,valid_from,source"});if(error)throw new SafeFiscalError("MUNICIPAL_PARAMETERS_INVALID","Não foi possível registrar os parâmetros municipais.");return{incidence:row.incidence,iss_rate_percent:row.iss_rate_percent,valid_from:row.valid_from,valid_until:row.valid_until};}
