import { z } from "zod";
import { getMunicipalParametersBaseUrl } from "../environments";
import { SafeFiscalError } from "../errors";
import { MtlsHttpClient } from "../client/mtls-http-client";

const serviceCodeSchema=z.string().regex(/^\d{2}\.\d{2}\.\d{2}\.\d{3}$/,"Código municipal deve ter o formato 00.00.00.000.");
const municipalityCodeSchema=z.string().regex(/^\d{7}$/);
const officialDateTimeSchema=z.string().regex(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})?$/,"Data oficial inválida.");
const aliquotaItemSchema=z.object({Incidencia:z.string().min(1),Aliq:z.coerce.number().finite().min(0).max(100),DtIni:officialDateTimeSchema,DtFim:officialDateTimeSchema.nullable()});
const aliquotaResponseSchema=z.object({aliquotas:z.record(serviceCodeSchema,z.array(aliquotaItemSchema).min(1)),mensagem:z.string()});
const nullableDate=officialDateTimeSchema.nullable();
const retentionsResponseSchema=z.object({mensagem:z.string().nullable(),retencoes:z.object({artigoSexto:z.object({habilitado:z.boolean(),historico:z.array(z.object({dataInicioVigencia:officialDateTimeSchema,dataFimVigencia:nullableDate})).nullable()}),retencoesMunicipais:z.array(z.object({descricao:z.string().nullable(),dataInicioVigencia:officialDateTimeSchema,dataFimVigencia:nullableDate,tiposRetencao:z.array(z.number().int().min(0).max(3)).nullable(),servicos:z.array(z.object({codigoCompleto:z.string().nullable(),historico:z.array(z.object({dataInicioVigencia:officialDateTimeSchema,dataFimVigencia:nullableDate})).nullable()})).nullable()})).nullable()})});
const specialRegimesResponseSchema=z.object({mensagem:z.string().nullable(),regimesEspeciais:z.record(z.string(),z.record(z.string(),z.array(z.object({situacao:z.number().int().min(1).max(3),dataInicio:officialDateTimeSchema,dataFim:nullableDate,observacoes:z.string().nullable()})))).nullable()});
const benefitResponseSchema=z.object({mensagem:z.string().nullable(),beneficio:z.object({codigoBeneficio:z.string().nullable(),descricao:z.string().nullable(),dataInicioVigencia:officialDateTimeSchema,dataFimVigencia:nullableDate,tipoBeneficio:z.number().int().min(1).max(4),tipoReducaoBC:z.unknown().nullable(),reducaoPercentualBC:z.number().nullable(),aliquotaDiferenciada:z.number().nullable(),restritoAoMunicipio:z.boolean().nullable(),servicos:z.array(z.object({codigoServico:z.string().nullable(),dataInicioVigencia:officialDateTimeSchema,dataFimVigencia:nullableDate})).nullable(),contribuintes:z.array(z.object({tipoInscricao:z.unknown().nullable(),inscricao:z.string().nullable(),dataInicioVigencia:officialDateTimeSchema,dataFimVigencia:nullableDate})).nullable()})});
export type MunicipalServiceCode=z.infer<typeof serviceCodeSchema>; export type AliquotaResponse=z.infer<typeof aliquotaResponseSchema>; export type MunicipalApiResult={url:string;status:number;data:AliquotaResponse}; export type MunicipalRetentions=z.infer<typeof retentionsResponseSchema>; export type MunicipalSpecialRegimes=z.infer<typeof specialRegimesResponseSchema>;
export const parseMunicipalServiceCode=(value:string):MunicipalServiceCode=>serviceCodeSchema.parse(value); export const issPercentToBasisPoints=(value:number)=>Math.round(value*100);

export class MunicipalParametersProvider {
  constructor(private readonly http=new MtlsHttpClient(),private readonly baseUrl=getMunicipalParametersBaseUrl()){}
  async getConvention(municipalityCode:string){const result=await this.http.getJson(`${this.baseUrl}/${municipalityCodeSchema.parse(municipalityCode)}/convenio`);if(result.status<200||result.status>=300)throw new SafeFiscalError("HTTP_ERROR","Não foi possível consultar os parâmetros municipais necessários.",result.status>=500);return z.record(z.string(),z.unknown()).parse(result.body);}
  async getAliquotaHistory(input:{municipalityCode:string;serviceCode:string}){return this.getValidated(`${this.baseUrl}/${municipalityCodeSchema.parse(input.municipalityCode)}/${parseMunicipalServiceCode(input.serviceCode)}/historicoaliquotas`,aliquotaResponseSchema);}
  async getSpecialRegimes(input:{municipalityCode:string;serviceCode:string;competence:string}):Promise<MunicipalSpecialRegimes>{return this.getValidated(`${this.baseUrl}/${municipalityCodeSchema.parse(input.municipalityCode)}/${parseMunicipalServiceCode(input.serviceCode)}/${this.competence(input.competence)}/regimes_especiais`,specialRegimesResponseSchema);}
  async getRetentions(input:{municipalityCode:string;competence:string}):Promise<MunicipalRetentions>{return this.getValidated(`${this.baseUrl}/${municipalityCodeSchema.parse(input.municipalityCode)}/${this.competence(input.competence)}/retencoes`,retentionsResponseSchema);}
  async getBenefit(input:{municipalityCode:string;benefitNumber:string;competence:string}){if(!input.benefitNumber.trim())throw new SafeFiscalError("MUNICIPAL_PARAMETERS_INVALID","O benefício municipal informado é inválido.");return this.getValidated(`${this.baseUrl}/${municipalityCodeSchema.parse(input.municipalityCode)}/${encodeURIComponent(input.benefitNumber)}/${this.competence(input.competence)}/beneficio`,benefitResponseSchema);}
  async getAliquota(input:{municipalityCode:string;serviceCode:string;competence:string}){return (await this.getAliquotaWithMeta(input)).data;}
  async getAliquotaWithMeta(input:{municipalityCode:string;serviceCode:string;competence:string}):Promise<MunicipalApiResult>{const service=parseMunicipalServiceCode(input.serviceCode);const result=await this.http.getJson(`${this.baseUrl}/${municipalityCodeSchema.parse(input.municipalityCode)}/${service}/${this.competence(input.competence)}/aliquota`);if(result.status<200||result.status>=300)throw new SafeFiscalError("HTTP_ERROR","Não foi possível consultar os parâmetros municipais necessários.",result.status>=500);try{return{url:result.url,status:result.status,data:aliquotaResponseSchema.parse(result.body)};}catch(error){if(error instanceof z.ZodError)throw new SafeFiscalError("MUNICIPAL_PARAMETERS_INVALID","Os parâmetros municipais recebidos estão em formato inválido.");throw error;}}
  private competence(value:string){if(!/^\d{4}-\d{2}-\d{2}$/.test(value))throw new SafeFiscalError("MUNICIPAL_PARAMETERS_INVALID","A competência informada é inválida.");return value;}
  private async getValidated<T extends z.ZodType>(url:string,schema:T):Promise<z.infer<T>>{const result=await this.http.getJson(url);if(result.status<200||result.status>=300)throw new SafeFiscalError("HTTP_ERROR","Não foi possível consultar os parâmetros municipais necessários.",result.status>=500);try{return schema.parse(result.body);}catch(error){if(error instanceof z.ZodError)throw new SafeFiscalError("MUNICIPAL_PARAMETERS_INVALID","Os parâmetros municipais recebidos estão em formato inválido.");throw error;}}
}
